language: node_js
node_js: node
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
matrix:
  include:
    - env: INSTALL_TYPE="locked"
    - env: INSTALL_TYPE="canary"
install: npm run install-$INSTALL_TYPE
addons:
  firefox: '51.0'
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: >-
      ojOP1apQn0mL+bXIajha5nILoDPMBQNy2q6Ead4rFFNrDsDEPnMSig5kx3qYz+6iLYIguYT1np1EvcZiyAH/912v4A/A7lf8D+9CR9pypDLz5vRY7WL08LGwk8ZQ1M3a5CKTVxsUsjlJam7av+vbIHxN/fb9Pf5y6q+MzKbds8F8JMfc3Gg1fh5IH+sUsvYdhV1Js3ia9zlUOdp45f0miCCPrtodVQs5B8YajdP0Hpj1peOqXgCzwNj3uXyR1FTp00bvI9z0jJXEl4W/u7w0GnDB/jwpmKFcj9SDlyz4XGlwkEOTN8fZsl6sKsNPgyVde7WFszR6NuakB/vKTIyibA4jMZ0khX6wn5keP7yJ6+h1g6fxQ/ac0BsUUgqFGFjLqXHpwutFXXAaUPuMirxXuu8/v++C/m7LpvT3zth8DjvIgqPcDmwab6fVKT6jFesnh53xTThtsNPnO1Ul6wi2X4Gaf9rUM6/ryj+46xvXGZvhjKISOF82DDfUv8+cm5sFp/ZRAsiEqg5Nfmuk3Dy1hCW5zs7qqhT6bVFsxB61eTIJ2qjg72kAcBdBwWFNUgnnYuD3lvn0y2dm4hWT8aXRl72lMFVS6qW2Fpzm8Chk2TXRGlrYUBYnNFVoDD9VD9gNxPGJ4IHQu+VgsElv5IbkvRbJwcD4vy5kaS3jS9pniyc=
  'on':
    tags: true
    repo: canjs/can-event-dom-enter
dist: xenial
services:
  - xvfb
